name: 'security-snyk-clojure-action'
description: 'Scans clojure repos with snyk'
inputs:
  twinGateKey:
    description: 'Replaces the need for a reverse proxy and uses Twingate VPN instead'
    required: true
  snykToken:
    description: 'snyk access token'
    required: true
  snykOrg:
    description: 'snyk org to write results to'
    required: true
  snykProject:
    description: 'snyk org to write results to'
    required: true
  noMonitor:
    description: 'allows skipping the snyk monitor step'
    required: false
  snykPolicy:
    description: 'the path to a .snyk file (https://docs.snyk.io/features/fixing-and-prioritizing-issues/policies/the-.snyk-file)'
    required: false
  
outputs:
  vulns: # id of output
    description: 'Array of vulnerable packages'
  # licenses: # id of output
  #   description: 'Array of license issues'
runs:
  using: 'docker'
  image: 'Dockerfile'
