name: 'security-snyk-clojure-action'
description: 'Scans clojure repos with snyk'
inputs:
  noMonitor:
    description: If set it will run `snyk test` instead of `snyk monitor`
    required: false
  snykToken:
    description: 'snyk access token'
    required: true
  snykOrg:
    description: 'snyk org to write results to'
    required: false
  snykProject:
    description: 'snyk project to write results to'
    required: false
  snykPolicy:
    description: 'the path to a .snyk file (https://docs.snyk.io/features/fixing-and-prioritizing-issues/policies/the-.snyk-file)'
    required: false
  snykTargetRef: 
    description: 'If true, set --target-reference to GITHUB_REF_NAME when running snyk monitor'
    required: false
  snykAdditionalArgs:
    description: 'additional args to pass to the snyk command'
    required: false
  debug:
    description: turn on debug logging
    required: false
outputs:
  vulns: # id of output
    description: 'Array of vulnerable packages'
  failure:
    description: 'true if there was an error, false if not'
runs:
  using: 'docker'
  image: 'Dockerfile'
