---
name: snyk_pr
 
on: [pull_request_target]

jobs:
 snyk_scan:
   runs-on: ubuntu-latest
   steps:
    - uses: twingate/github-action@v1
      with:
        service-key: ${{ secrets.TWINGATE_KEY }}
    - name: checkout the current PR
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Run Clojure Snyk Scan
      id: scan
      uses: puppetlabs/security-snyk-clojure-action@main
      with:
        snykToken: ${{ secrets.SNYK_PE_TOKEN }}
        snykOrg: 'puppet-enterprise'
        snykProject: 'pe-console-services'
        snykPolicy: '.snyk'
        noMonitor: "true"
    - name: Check output
      if: steps.scan.outputs.vulns != ''
      run: echo "Vulnerabilities detected; ${{ steps.scan.outputs.vulns }}" && exit 1
