---
name: Clojure Snyk Check
 
on:
 pull_request:
    branches:
      - main

jobs:
 snyk_clojure:
   runs-on: ubuntu-latest
   steps:
    - name: checkout the current PR
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Run Clojure Snyk Scan
      id: scan
      uses: puppetlabs/security-snyk-clojure-action@v1.1.0
      with:
        snykToken: ${{ secrets.SNYK_TOKEN }}
        rproxyKey: ${{ secrets.RPROXY_KEY }}
        snykOrg: 'sectest'
        snykProject: 'puppetserver'
        snykPolicy: '.snyk'
    - name: Check output
      if: steps.scan.outputs.vulns != ''
      run: echo "Vulnerabilities detected; ${{ steps.scan.outputs.vulns }}" && exit 1
