---
name: Clojure Snyk Check
 
on:
 pull_request:
    branches:
      - main

jobs:
 snyk_clojure:
   runs-on: ubuntu-latest
   steps:
    - uses: twingate/github-action@v1
      with:
        service-key: ${{ secrets.TWINGATE_KEY }} # TWINGATE_PUBLIC_REPO_KEY for public repos
    - name: checkout the current PR
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Run Clojure Snyk Scan
      id: scan
      uses: puppetlabs/security-snyk-clojure-action@v2
      with:
        snykToken: ${{ secrets.SNYK_TOKEN }}
        snykPolicy: '.snyk'
    - name: Check output
      if: steps.scan.outputs.vulns != ''
      run: echo "Vulnerabilities detected; ${{ steps.scan.outputs.vulns }}" && exit 1
